name: JavaWorkflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  grussformel: Guten Tag

jobs:
  build-test:
    runs-on: ubuntu-latest
    needs: console-variables
    strategy:
          matrix:
            version: [21, 17, 11]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{matrix.version}}

      - name: Build and Test
        run: mvn -B clean verify

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/

  linter:
    runs-on: ubuntu-latest
    needs: console-variables

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: lint check
        run: mvn checkstyle:checkstyle

      - name: archive lint check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: target/checkstyle-result.xml

  console-variables:
    runs-on: ubuntu-latest
    env:
      begruesster: Yordan
    steps:
      - name: Console results
        env:
          passwortnutzen: Bankkonto
        run: echo $grussformel $begruesster, das Passwort f√ºr $passwortnutzen ist ${{secrets.PASSWORT_NUTZEN}}
